[project]
name = "message-extensions"
version = "0.1.0"
description = "message extension tests"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "microsoft-teams-apps",
]

[tool.uv.sources]
microsoft-teams-apps = { workspace = true }
