[project]
name = "cards"
version = "0.1.0"
description = "app testing adaptive cards"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "microsoft-teams-apps",
  "microsoft-teams-cards"
]

[tool.uv.sources]
microsoft-teams-apps = { workspace = true }
