[project]
name = "dialogs"
version = "0.1.0"
description = "a test testing out dialogs/task-modules"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "microsoft-teams-apps",
]

[tool.uv.sources]
microsoft-teams-apps = { workspace = true }
